import type { GlobalThemeOverrides } from 'naive-ui'

export default {
  common: {
    borderRadius: '3px',
    primaryColor: '#18a058',
    primaryColorHover: '#36ad6a',
    primaryColorSuppl: '#36ad6a',
    primaryColorPressed: '#0c7a43',

    infoColor: '#2080f0',
    infoColorHover: '#4098fc',
    infoColorPressed: '#1060c9',
    infoColorSuppl: '#4098fc',

    successColor: '#18a058',
    successColorHover: '#36ad6a',
    successColorPressed: '#0c7a43',
    successColorSuppl: '#36ad6a',

    warningColor: '#f0a020',
    warningColorHover: '#fcb040',
    warningColorPressed: '#c97c10',
    warningColorSuppl: '#fcb040',

    errorColor: '#d03050',
    errorColorHover: '#de576d',
    errorColorPressed: '#ab1f3f',
    errorColorSuppl: '#de576d',
  },
  Menu: {
    colorInverted: '#0000',
    itemColorHoverInverted: '#0000',
    itemColorActiveInverted: '#18a058',
    itemColorActiveHoverInverted: '#18a058',
    itemColorActiveCollapsedInverted: '#18a058',
    itemTextColorInverted: '#BBB',
    itemTextColorHoverInverted: '#FFF',
    itemTextColorChildActiveInverted: '#FFF',
    itemTextColorHorizontalInverted: '#BBB',
    itemTextColorActiveHoverInverted: '#FFF',
    itemTextColorActiveInverted: '#FFF',
    itemTextColorChildActiveHoverInverted: '#FFF',
    itemTextColorHoverHorizontalInverted: '#FFF',
    itemTextColorChildActiveHorizontalInverted: '#FFF',
    itemTextColorChildActiveHoverHorizontalInverted: '#FFF',
    itemTextColorActiveHorizontalInverted: '#FFF',
    itemIconColorActiveInverted: '#FFF',
    itemIconColorHoverInverted: '#FFF',
    itemIconColorInverted: '#BBB',
    itemTextColorActiveHoverHorizontalInverted: '#FFF',
    itemIconColorActiveHoverInverted: '#FFF',
    itemIconColorChildActiveInverted: '#FFF',
    itemIconColorChildActiveHoverInverted: '#FFF',
    itemIconColorCollapsedInverted: '#BBB',
    itemIconColorHorizontalInverted: '#BBB',
    itemIconColorHoverHorizontalInverted: '#FFF',
    itemIconColorActiveHorizontalInverted: '#FFF',
    itemIconColorActiveHoverHorizontalInverted: '#FFF',
    arrowColorHoverInverted: '#FFF',
    arrowColorInverted: '#BBB',
    itemIconColorChildActiveHoverHorizontalInverted: '#FFF',
    itemIconColorChildActiveHorizontalInverted: '#FFF',
    arrowColorActiveInverted: '#FFF',
    arrowColorActiveHoverInverted: '#FFF',
    arrowColorChildActiveInverted: '#FFF',
    arrowColorChildActiveHoverInverted: '#FFF',
    groupTextColorInverted: '#AAA',

    // itemColor: '#0000',
    // itemColorHover: '#0000',
    // itemColorActive: '#18a058',
    // itemColorActiveHover: '#18a058',
    // itemColorActiveCollapsed: '#18a058',
    // itemTextColor: '#BBB',
    // itemTextColorHover: '#FFF',
    // itemTextColorChildActive: '#FFF',
    // itemTextColorHorizontal: '#BBB',
    // itemTextColorActiveHover: '#FFF',
    // itemTextColorActive: '#FFF',
    // itemTextColorChildActiveHover: '#FFF',
    // itemTextColorHoverHorizontal: '#FFF',
    // itemTextColorChildActiveHorizontal: '#FFF',
    // itemTextColorChildActiveHoverHorizontal: '#FFF',
    // itemTextColorActiveHorizontal: '#FFF',
    // itemIconColorActive: '#FFF',
    // itemIconColorHover: '#FFF',
    // itemIconColor: '#BBB',
    // itemTextColorActiveHoverHorizontal: '#FFF',
    // itemIconColorActiveHover: '#FFF',
    // itemIconColorChildActive: '#FFF',
    // itemIconColorChildActiveHover: '#FFF',
    // itemIconColorCollapsed: '#BBB',
    // itemIconColorHorizontal: '#BBB',
    // itemIconColorHoverHorizontal: '#FFF',
    // itemIconColorActiveHorizontal: '#FFF',
    // itemIconColorActiveHoverHorizontal: '#FFF',
    // arrowColorHover: '#FFF',
    // arrowColor: '#BBB',
    // itemIconColorChildActiveHoverHorizontal: '#FFF',
    // itemIconColorChildActiveHorizontal: '#FFF',
    // arrowColorActive: '#FFF',
    // arrowColorActiveHover: '#FFF',
    // arrowColorChildActive: '#FFF',
    // arrowColorChildActiveHover: '#FFF',
    // groupTextColor: '#AAA',
  },
} as GlobalThemeOverrides
